slurm: True
default-resources:
  - mem_mb=8000
  - slurm_account=jonth0
  - slurm_partition=standard
  - runtime=300
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
jobscript: "/home/jonth/eastbay_paper/slurm-jobscript.sh"
