slurm: False
config:
  - unified_path="/scratch/unified"
  - basedir="/home/jonth/eb_dl/paper_repo"
  - workdir="/scratch/jonth_root/jonth0/jonth/eastbay_paper/pipeline"
  - bcftools_path="~/.local/bin/bcftools"
  - scrm_path="~/eb_dl/paper_repo/lib/scrm/scrm"
