slurm: True
default-resources:
  - mem_mb=4000
  - slurm_account=stats_dept1
  - slurm_partition=standard
  - runtime=60
local-cores: 4
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 400
keep-going: True
rerun-incomplete: True
printshellcmds: True
jobscript: "/home/jonth/eb_dl/paper_repo/slurm-jobscript.sh"
config:
  - unified_path="/nfs/turbo/lsa-jonth/jonth/unified/"
  - basedir="/home/jonth/eb_dl/paper_repo"
  - workdir="/scratch/jonth_root/jonth0/jonth/eastbay_paper/pipeline"
  - bcftools_path="/home/jonth/.local/bin/bcftools"
  - scrm_path="/home/jonth/eb_dl/paper_repo/lib/scrm/scrm"
  - psmc_path="/home/jonth/eb_dl/paper_repo/lib/psmc/psmc"
  - figures_path="/nfs/turbo/lsa-jonth/jonth/pipeline/figures"
