slurm: True
default-resources:
  - mem_mb=4000
  - slurm_account=jonth0
  - slurm_partition=standard
  - runtime=60
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
jobscript: "/home/jonth/eastbay_paper/slurm-jobscript.sh"
bcftools_cmd: "~/.local/bin/bcftools"
workdir: "/scratch/jonth_root/jonth0/jonth/eastbay_paper/pipeline"
basedir: "/home/jonth/eastbay_paper"
